changelog:
  exclude:
    labels:
      - exclude from release

  categories:
    - title: Breaking Changes
      labels:
        - breaking change
        - breaking

    - title: Bug Fixes
      labels:
        - bug fix
        - fix

    - title: Features
      labels:
        - feature
        - feat

    - title: Other Changes
      labels:
        - change
