env:
  browser: true
  es6: true
  node: true

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/strict-type-checked"
  - "plugin:@typescript-eslint/stylistic-type-checked"

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json

plugins:
  - "@stylistic/js"
  - "@typescript-eslint"
  - "@stylistic/ts"

root: true

rules:
  "@stylistic/js/semi": "off"
  "@stylistic/ts/semi":
    - error
    - always

  "@stylistic/js/indent": "off"
  "@stylistic/ts/indent":
    - error
    - 2

  "@stylistic/js/quotes": "off"
  "@stylistic/ts/quotes":
    - error
    - single

  "@stylistic/js/linebreak-style":
    - error
    - windows

  "@stylistic/js/comma-dangle": "off"
  "@stylistic/ts/comma-dangle":
    - error
    - always-multiline

  "@stylistic/js/no-extra-parens": "off"
  "@stylistic/ts/no-extra-parens": error

  no-useless-rename: error
  object-shorthand: error

  "@stylistic/js/no-multiple-empty-lines":
    - error
    - max: 1
      maxBOF: 0
      maxEOF: 0

  "@typescript-eslint/array-type":
    - error
    - default: array-simple
      readonly: array-simple

  "@stylistic/ts/member-delimiter-style": error
  "@typescript-eslint/restrict-template-expressions": "off"
