version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0

executors:
  node_18:
    docker:
      - image: cimg/node:18.20.3
    working_directory: &working_directory ~/gen-unit

commands:
  npm_publish:
    steps:
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

jobs:
  test_and_build:
    executor: node_18
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-gen-unit-{{ checksum "package-lock.json" }}
            - v1-deps-gen-unit-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-gen-unit-{{ checksum "package-lock.json" }}
      - run:
          name: Test
          command: npm test
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: *working_directory
          paths:
            - .

  upload_coverage:
    executor: node_18
    steps:
      - attach_workspace: &attach_workspace
          at: *working_directory
      - codecov/upload:
          file: coverage/*.json

  publish_to_npm:
    executor: node_18
    steps:
      - attach_workspace: *attach_workspace
      - npm_publish

workflows:
  main-workflow:
    jobs:
      - test_and_build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - upload_coverage:
          requires:
            - test_and_build
          filters:
            branches:
              only: /master/

      - publish_to_npm:
          context: npm
          requires:
            - test_and_build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
